name: Check Code

on:
  push:
    branches:
      - 'feat/**'
      - 'fix/**'
      - 'refactor/**'
      - 'improvement/**'
      - 'hotfix/**'
  pull_request:
    branches:
      - 'feat/**'
      - 'fix/**'
      - 'refactor/**'
      - 'improvement/**'
      - 'hotfix/**'

jobs:
  code_quality:
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP Environment
        uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: "8.2"

      - uses: actions/checkout@v3

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          cd src
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('src/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install Dependencies
        run: |
          cd src
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Run Laravel Pint
        id: run_pint
        run: |
          cd src
          if ! vendor/bin/pint --config pint.json --test; then
            echo "❌ Formatting failed. Please run Laravel Pint to fix the code style."
            exit 1
          fi

      - name: Run Larastan
        id: run_larastan
        run: |
          cd src
          if ! php -d memory_limit=5G vendor/bin/phpstan analyse --no-progress app; then
            echo "❌ Larastan detected issues. Please run larastan before committing."
            exit 1
          fi
